app = "fredags-dak-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV="production"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

#[[services.ports]]
#  #internal_port = 443
#  handlers = ["tls", "http"]
#  port = "443"
#  #processes = ["app"]